#pragma once

namespace game
{
namespace ui
{

static enum UICONTEXT_ITEMS_INIT
{
	UICONTEXTITEM_INIT_WIREINPUT = 0,
	UICONTEXTITEM_INIT_WIREOUTPUT,
	UICONTEXTITEM_INIT_EDIT,
	UICONTEXTITEM_INIT_UNWIREINPUT,
	UICONTEXTITEM_INIT_UNWIREOUTPUT,
	UICONTEXTITEM_INIT_REMOVE,

	//last
	NUM_UICONTEXTITEM_INIT
};

static enum UICONTEXT_ITEMS_SELECTPORT
{
	UICONTEXTITEM_SELECTPORT_ALL = 0,

	//last
	NUM_UICONTEXTITEM_SELECTPORT
};

//Type of context menu
static enum UICONTEXT_TYPE
{
	UICONTEXT_INIT = 0,
	UICONTEXT_SELECTINPUT_WIRE,
	UICONTEXT_SELECTOUTPUT_WIRE,
	UICONTEXT_SELECTINPUT_UNWIRE,
	UICONTEXT_SELECTOUTPUT_UNWIRE,

	//last
	NUM_UICONTEXT_TYPES
};

//Type of UI component
static enum UI_DATATYPE
{
	UI_LUACOMPONENT = 0,
	UI_MENU,
	UI_TREE,
	UI_CONTEXT,
	UI_EDIT,
	UI_WINDOW,
	UI_CONSOLE,

	//last
	NUM_UI_DATATYPES
};

}
}
